name: Gradle Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-13, windows-latest]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.0+35'
        distribution: 'temurin'
        # Ensure an x86_64 JDK is used for all builds, especially crucial for macOS Intel target
        architecture: 'x64'
    - name: Verify Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Give permissions
      run: chmod +x ./gradlew
    - name: Build and Package Application
      if: runner.os == 'macOS'
      run: iconutil -c icns src/main/resources/icon.iconset
    - name: Build and Package Application
      run: |
        ls src/main/resources
        ./gradlew --info --stacktrace jpackage -PappVersion=${{ github.ref_name }}
    - name: Upload PKG as an artifact
      uses: actions/upload-artifact@v4
      if: runner.os == 'macOS'
      with:
        name: budget-pkg
        path: build/jpackage/*.pkg
    - name: Upload EXE as an artifact
      uses: actions/upload-artifact@v4
      if: runner.os == 'Windows'
      with:
        name: budget-exe
        path: build/jpackage/*.exe
    - name: Upload MSI as an artifact
      uses: actions/upload-artifact@v4
      if: runner.os == 'Windows'
      with:
        name: budget-msi
        path: build/jpackage/*.msi
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build # Ensures this job runs only after all matrix builds are successful
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') # Only run on tag pushes
    permissions:
      contents: write # Required to create a release and upload assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts # All artifacts will be downloaded into subdirectories here

      - name: List downloaded artifacts (for debugging)
        run: ls -R artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/budget-pkg/*.pkg
            artifacts/budget-exe/*.exe
            artifacts/budget-msi/*.msi